---
#create a jenkins-pod and also  perfom necessary port mapping
apiVersion: v1
kind: Pod
metadata: 
 name: jenkins-pod
 lables: 
  type: ci-cd
spec: 
 containers:
  - name: jenkins
    image: jenkins/jenkins
  - ports:
     - containerPort: 8080
       hostPort: 8080
...