---
#Create a replication controller for creating 3 replicas of httpd
apiVersion: v1
kind: ReplicationController
metadata: 
 name: httpd-rc
 labels:
  author: kireeti
  type: rc
spec:
 replicas: 3
 template:
  metadata:
   name: httpd-pod
   labels: 
    author: kireeti
 spec: 
  containers:
   - name: myhttpd
     image: httpd
     ports: 
      - containerPort: 80
        hostPort: 8080
...