---
# Create a service defintion file for port mapping an nginx pod
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec: 
 type: NodePort
 ports: 
  - targetPort: 80
    port: 80
    hostPort: 30008
 selector:
  matchLables:
   author: kireeti
   type: proxy
...